version: '3'
services:
    web:
        build:
          context : .
          dockerfile: ./UI/WebMain/test-project/Dockerfile
        tty: true

        ports:
          - 8000:8000
    nginx:
        image: nginx:latest