# Generated by Django 4.0 on 2022-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20220331_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('CHOOSE', 'choose'), ('JAVA', 'Java'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'Python'), ('.NET', '.Net')], default='', max_length=200, null=True),
        ),
    ]
