# Generated by Django 4.0.4 on 2022-04-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
