# Generated by Django 3.0.5 on 2022-04-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_alter_profile_id_alter_profile_language'),
        ('UI', '0005_remove_profile_username'),
    ]

    operations = [
    ]
