# Generated by Django 3.2.12 on 2022-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_alter_profile_language'),
        ('UI', '0006_merge_20220428_1413'),
    ]

    operations = [
    ]
