# Generated by Django 3.2.12 on 2022-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_merge_20220528_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('CHOOSE', 'choose'), ('JAVA', 'Java'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'Python'), ('.NET', '.Net')], default='', max_length=200, null=True),
        ),
    ]
