# Generated by Django 3.0.5 on 2022-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0008_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
