# Generated by Django 4.1.5 on 2023-01-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=1000, null=True)),
                ("email", models.EmailField(blank=True, max_length=1000, null=True)),
                ("phone_number", models.PositiveBigIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                "db_table": "interns",
            },
        ),
    ]
