# Generated by Django 3.0.6 on 2022-03-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
