# Generated by Django 3.0.6 on 2022-03-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20220325_0440'),
        ('UI', '0002_alter_profile_avatar'),
    ]

    operations = [
    ]
